### ISSUE TITLE
Сохранять базу данных в docker volume

### ISSUE THREAD

**Issue by klpx** [pastegraph/production#4]
Для докер компоуз:
```
  store:
    image: pashabezborod/pastegraph-webui
    environment:
      DB_PATH: /myvolume/db.sqlite
    volumes:
      - storedata:/myvolume

volumes:
  storedata:
```

А в приложении нужно сделать,  чтобы использовалась переменная DB_PATH
